"""Initial migration


Revision ID: 2e8ed2736af5
Revises: 
Create Date: 2024-07-31 14:24:08.623461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8ed2736af5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'payment_gateway_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column(
        'payment_gateway_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_gateway_provider')
    op.drop_column('users', 'payment_gateway_customer_id')
    # ### end Alembic commands ###
