name: Trigger auto deployment for never-bored-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/never-bored-backend-AutoDeployTrigger-60c23b77-9b0d-4343-bf43-0b2249ec35f8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NEVERBOREDBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NEVERBOREDBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NEVERBOREDBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: neverbored.azurecr.io
          registryUsername: ${{ secrets.NEVERBOREDBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NEVERBOREDBACKEND_REGISTRY_PASSWORD }}
          containerAppName: never-bored-backend
          resourceGroup: pythoncontainer
          imageToBuild: neverbored.azurecr.io/never-bored-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


